CXX 		 = clang++
CXXFLAGS = -O2 -Wall -Wextra -std=c++0x
LDFLAGS  = -L/usr/local/lib -L/usr/local/opt/boost
INCLUDES = -Iinclude -I/usr/local/include -I/usr/local/include/boost -I/usr/local/opt/boost/include
LIBS 		 = -lboost_program_options-mt -lboost_system-mt

include ./Makefile.common
